### ISSUE TITLE
ExaTENSOR BLAS libraries

### ISSUE THREAD

**Issue by DmitryLyakh** [ORNL-QCI/exatn#10]
Linking to BLAS libraries required by ExaTENSOR/TALSH is a mess because there is no standard way of doing so. Below are the details how different BLAS libraries should be linked, namely which specific environment variables the ExaTENSOR/TALSH Makefile expects for each particular BLAS library. It is highly unlikely we can import this from CMAKE, so I would recommend to require the user to explicitly provide the necessary PATHs for the chosen BLAS library (BLAS_LIB) and then add the necessary linked libraries for each choice inside CMakeLists.txt

ATLAS (any default Linux/Mac BLAS):
BLASLIB=ATLAS
PATH_BLAS_ATLAS (where libblas.so is)
Linked libraries: libblas

MKL (Intel MKL):
BLASLIB=MKL
PATH_INTEL (intel root directory, for example /opt/intel)
Linked libraries (GNU compiler): libmkl_intel_lp64, libmkl_gnu_thread, libmkl_core, libpthread, libm, libdl
Linked libraries (Intel compiler): libmkl_intel_lp64, libmkl_intel_thread, libmkl_core, libpthread, libm, libdl, libiomp5

ACML:
BLASLIB=ACML
PATH_BLAS_ACML (where libacml_mp.so is)
Linked libraries: libacml_mp

ESSL (IBM ESSL on Summit):
BLASLIB=ESSL
PATH_BLAS_ESSL (where libessl.so is)
PATH_IBM_XL_CPP (where IBM XL C++ libraries are)
PATH_IBM_XL_FOR (where IBM XL Fortran libraries are)
PATH_IBM_XL_SMP (where IBM XL SMP libraries are)
Linked libraries: libessl, libxlf90_r, libxlfmath

**Comment by amccaskey** [comment]
Committed an update for this. Tested for ATLAS and MKL. I don't have ACML or ESSL

**Comment by DmitryLyakh** [comment]
The latest devel branch should have proper support for all four BLAS libraries.
