### ISSUE TITLE
devel build fail due to if(NOT EXISTS ${BLAS_PATH}/libblas.so)

### ISSUE THREAD

**Issue by amccaskey** [ORNL-QCI/exatn#12]
I believe you need to update to ```if(NOT EXISTS "${BLAS_PATH}/libblas.so")```

**Comment by DmitryLyakh** [comment]
Is it always static on Mac OS, libblas.a?

**Comment by DmitryLyakh** [comment]
Should be fixed now, I am now testing for either libblas.so or libblas.a.
