### ISSUE TITLE
exatn-config executable

### ISSUE THREAD

**Issue by amccaskey** [ORNL-QCI/exatn#18]
I'd like to create an executable called exatn-config that downstream users can leverage in standard Makefile builds. For downstream CMake users, we will have them just use exatn::exatn targets, but for Makefile users we need to be able to provide the include headers and link line that they can integrate in their makefiles. My inspiration for this is the llvm-config executable.

Users should be able to run commands like this 

```
$ exatn-config --libs (to return the link line)
$ exatn-config --includes (to get the include paths)
$ exatn-config --ldflags (to get any linker flags)
$ exatn-config --cxxflags (to get all cxx flags)
```

I think we could do this pretty easily with a python script. We could reference necessary CMake variables in that script and use CMake configure_command() to write those concrete variables.

**Comment by DmitryLyakh** [comment]
Great idea.

**Comment by osbornjd** [comment]
I'll try and take a look at this sometime this week.

**Comment by DmitryLyakh** [comment]
We need to document in README how to use exatn-config and how user applications are supposed to include exatn headers and libraries.
