### ISSUE TITLE
CPPMicroservices fail two tests

### ISSUE THREAD

**Issue by DmitryLyakh** [ORNL-QCI/exatn#20]
On branch devel: After I have updated TensorMethod interface, which is now called TensorFunctor, two tests (NumServerTester, TensorRuntimeTester) began to fail with that below. I have no idea why it is complaining now as I see no relation to CPPMicroservices in my changes. Note that I built the MPI version of ExaTN (gcc/8.2.0, mpich/3.2.1).

terminate called after throwing an instance of 'std::runtime_error'
  what():  Bundle#3 start failed: libantlr4-runtime.so.SOVERSION: cannot open shared object file: No such file or directory
Aborted

**Comment by DmitryLyakh** [comment]
I have just built the same devel branch without MPI, it passes the tests. Alex, apparently something got screwed up in the MPI-enabled build with respect to CPPMicroservices configuration. Could you please check?

**Comment by amccaskey** [comment]
I just built, installed, and ran tests with OpenMPI and everything worked fine. Also note that the CI is building everything with CUDA and MPICH, and the tests/CI are still passing.

**Comment by DmitryLyakh** [comment]
Hmm, do you have any idea why CPPMicroservices is trying to open libantlr4-runtime.so.SOVERSION with unresolved version on my machine?

**Comment by amccaskey** [comment]
CppMicroServices is not necessarily trying to open libantlr, but it is trying to load the libexatn-taprol-parser.so plugin, which links to libantr4. And if it can't make that link, then the plugin will not load, and CppMicroServices will throw the error.

**Comment by amccaskey** [comment]
This was due to CMake appending suffix 'd' to libraries on debug builds. Turning that off...
