### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by DmitryLyakh** [ORNL-QCI/exatn#21]
Recently (branch devel) I decided to use talsh::Tensor instead of TensorDenseBlock in tensor_method.hpp (inside TensorMethod interface which is now called TensorFunctor). Consequently, I went inside exatn-py.cpp and replaced TensorDenseBlock with talsh::Tensor, which necessitated inclusion of talshxx.hpp, which in turn includes talsh.h, whic is a C header with many symbols in GLOBAL scope. This C part did not build in exatn-py.cpp. So I got rid of it. But now it does not look like I can refer to talsh::Tensor in the Python bindings (see commented block there). What would a solution be here?

**Comment by amccaskey** [comment]
I just uncommented the TensorFunctor py::class code and added talshxx and tensor_method to the includes, and it built for me, no C errors

**Comment by amccaskey** [comment]
To use this, we will need to expose talsh::Tensor (or at least some of its API) to Python in exatn-py.cpp. I can handle this. 

It would be helpful though to see a full example of using TensorFunctor and the numerics API. Can you put that together?

**Comment by DmitryLyakh** [comment]
Ok, let me try to rebuild from a clean state ...

**Comment by DmitryLyakh** [comment]
I had to add a new argument "tag" to exatn::NumServer::registerTensorMethod() in order to distinguish different functors of the same class. We need to correct Python binding for this function. I also added registerTensorMethod, getTensorMethod, registerExternalData, getExternalData, and getLocalTensor to high-level exatn_numerics.hpp header. We need Python bindings for these.

**Comment by DmitryLyakh** [comment]
I almost finished the mechanism for getLocalTensor() API. I had to modify the interface for this function such that it returns a std::future<std::shared_ptr<talsh::Tensor>> now. Please check consistency of Python bindings for this API function.

**Comment by DmitryLyakh** [comment]
Actually just realized that I will need to modify it again to return std::shared_ptr<talsh::Tensor>, so let's hold on on it.

**Comment by DmitryLyakh** [comment]
Ok, fixed, please check exatn::getLocalTensor() and exatn::NumServer::getLocalTensor() interface. This is its final version. We need to Pybind it properly such that numpy array is returned instead of talsh::Tensor.
