### ISSUE TITLE
Python tests error: incompatible function arguments.

### ISSUE THREAD

**Issue by DaniloZZZ** [ORNL-QCI/exatn#29]
Hi, i try to run  `python/tests/test-tensorRuntime.py` 
and get the following error: 
  ```
File "test-tensorRuntime.py", line 23, in <module>
    create_tensor1.setTensorOperand(tensor1)
TypeError: setTensorOperand(): incompatible function arguments. The following argument types are supported:
    1. (self: exatn._pyexatn.TensorOperation, arg0: exatn::numerics::Tensor, arg1: bool) -> None

Invoked with: <exatn._pyexatn.TensorOpCreate object at 0x7f272d4af3b0>, <exatn._pyexatn.Tensor object at 0x7f272d4af2d0>

```

changing line 20 from `create_tensor0.setTensorOperand(tensor0)` to ` create_tensor0.setTensorOperand(tensor0, True)` helps: same error is raised on next line.

- OS: Arch Linux x86_643
- Python 3.7.3 
- gcc and g++: 8.3.0
- cuda: 10.1.105-12

compiled with this:
```
cmake .. -DEXATN_BUILD_TESTS=TRUE -DPYTHON_INCLUDE_DIR=(python
-c "import sysconfig; print(sysconfig.get_paths()['platinclude'])") -DENABLE_CUDA=True
```

**Comment by amccaskey** [comment]
The python API has been updated significantly since this post. Please pull the latest and rebuild. There are a number of examples available in python/examples.
