### ISSUE TITLE
TensorRuntime test failure

### ISSUE THREAD

**Issue by DmitryLyakh** [ORNL-QCI/exatn#3]
src/runtime/tests/TensorRuntimeTester 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Bundle#5 start failed: libtalsh.so: cannot open shared object file: No such file or directory
Aborted (core dumped)

**Comment by amccaskey** [comment]
is this on devel?

**Comment by amccaskey** [comment]
The example-tensor-method plugin was causing this. But I turned off its build and install until we get back to work on the tensor method stuff. 

One quick suggestion is to delete ~/.exatn/plugins/* and try to make install again.

**Comment by amccaskey** [comment]
Can't reproduce on devel. 

And looking, you should only have 4 plugins installed: mpi_rpc, runtime_executor, runtime_graph, and runtime_optimizer. So the 5th (Bundle#5) might be the example tensor method plugin, just delete it and make sure that its not installing when you run make install. If it does, then in build dir run rm -rf Cmake* and re-run cmake and make.

**Comment by DmitryLyakh** [comment]
This was a clean <devel> branch build on my laptop which I did from scratch, however indeed I did not delete old ~/.exatn/plugins directory. Probably that was causing the failure. I will try again later.

**Comment by DmitryLyakh** [comment]
Yep, that was the case. We need to document this in README (the necessity to delete ~/.exatn directory).
