### ISSUE TITLE
Custom install locations not supported

### ISSUE THREAD

**Issue by khanley6** [ORNL-QCI/exatn#31]
Setting `CMAKE_INSTALL_PREFIX` installs all libraries as expected however this causes tests to fail at runtime with the following error:
```
[service-registry] Could not open plugin directory.
Could not find service with name eager-dag-executor. Perhaps the service is not Identifiable.
#ERROR(exatn::service): Invalid ExaTN service: eager-dag-executor in the Service Registry.
Could not find service with name boost-digraph. Perhaps the service is not Identifiable.
#ERROR(exatn::service): Invalid ExaTN service: boost-digraph in the Service Registry.
[login2:32431] *** Process received signal ***
[login2:32431] Signal: Segmentation fault (11)
[login2:32431] Signal code: Address not mapped (1)
[login2:32431] Failing at address: (nil)
```

This is due to `exatn::initialize()` calling `serviceRegistry->initialize` with no arguments, which in turn causes the `exatnPluginPath` to be set to `$HOME/.exatn/plugins` by default.

**Comment by amccaskey** [comment]
Thanks for pointing this out. I just pushed a fix to master and devel. Pull and make sure the tests pass for you.

**Comment by khanley6** [comment]
All tests pass now. Thanks a million for the quick fix!
