### ISSUE TITLE
ExaTn Python Example Throws Undefined Symbol error.

### ISSUE THREAD

**Issue by cameton** [ORNL-QCI/exatn#38]
When running [this](https://github.com/ORNL-QCI/exatn/blob/master/python/examples/simple.py) simple ExaTn benchmark, ExaTn throws an error and becomes unresponsive. 

Python seems to be trying to use an anaconda MKL library, despite ExaTn being built with a specific, separate MKL installation.

Output:
```
(base) $ ipython simple.py
#DEBUG(exatn::runtime::TensorRuntime)[MAIN_THREAD]: DAG executor set to lazy-dag-executor + talsh-node-executor
#DEBUG(exatn::runtime::TalshNodeExecutor): TAL-SH initialized with Host buffer size of 1072693248 bytes
INTEL MKL ERROR: /home/.../anaconda3/lib/libmkl_avx.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.
```

ExaTn CMake Configuration:
```
cmake ..  -DEXATN_BUILD_TESTS=TRUE -DCMAKE_BUILD_TYPE=Release -DPATH_INTEL_ROOT=$MKLROOT/.. -DBLAS_LIB=MKL -DCMAKE_INSTALL_PREFIX=~/.exatn
```

OS Version Information:
Linux version 3.10.0-957.10.1.el7.x86_64 (mockbuild@x86-040.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Feb 7 07:12:53 UTC 2019

**Comment by DmitryLyakh** [comment]
This is a known issue related to the MKL library linkage. Can you try using LD_PRELOAD as recommended here:
https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/748309

**Comment by cameton** [comment]
This has resolved the issue, thank you.
