### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by otbrown** [ORNL-QCI/exatn#44]
I'm trying to build exatn so I can use it in conjunction with tnqvm, but I've hit a couple of issues.

First, I had to comment out lines 17-31 in tpls/CMakeLists.txt, where it does `git submodule update --init --recursive`, as git complains that this should be run in a top-level directory and gives a non-zero return value. Given the advice in the README to run `git submodule update --init --recursive` in the correct place, I suspect this part of the cmake is redundant anyway.

Second, I can get the libraries to build, but fail at runtime with an error while loading shared libraries, specifically libtalsh. In the link line during build, talsh is linked with a full path to its relative location, but this is no longer valid once moved to the install directory. I can fix it by manually relinking with `-L<path-to-install-directory>/lib -ltalsh`, but I'm hoping for a CMake solution...

All help appreciated!

Relevant extract from `ldd libexatn.so`:
```
        ../../../installdir/lib/libtalsh.so => not found
        ../../../../installdir/lib/libtalsh.so => not found
        ../../../installdir/lib/libtalsh.so => not found
        ../../../installdir/lib/libtalsh.so => not found
```

**Comment by DmitryLyakh** [comment]
How are you building it exactly? Can you copy paste the full list of commands you are using to build ExaTN?

**Comment by otbrown** [comment]
Sure thing, after the usual `mkdir build`, `cd build`, I run the following script:
```
#!/bin/bash

BUILD_TYPE=Release
BUILD_TESTS=TRUE
BLAS_LIB=MKL
INTEL_ROOT=/opt/intel
MPI_LIB=MPICH  # IMPI is ABI compatible with mpich
MPI_ROOT=${I_MPI_ROOT} # set by module MPI

INSTALL_DIR=$(pwd)/../installdir

CXX=g++
CC=gcc

cmake \
  -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
  -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
  -DCMAKE_CXX_COMPILER=${CXX} \
  -DCMAKE_C_COMPILER=${CC} \
  -DEXATN_BUILD_TESTS=${BUILD_TESTS} \
  -DBLAS_LIB=${BLAS_LIB} \
  -DPATH_INTEL_ROOT=${INTEL_ROOT} \
  -DMPI_LIB=${MPI_LIB} \
  -DMPI_ROOT_DIR=${MPI_ROOT} \
  ..
  ```
  
  Followed, by `make install`.

**Comment by DmitryLyakh** [comment]
$INSTALL_DIR cannot reside inside ExaTN source. You need to specify an outside location. I would recommend rebuilding everything from scratch at this point. You will not need to make any edits anywhere in CMAKE, etc. Once you fix INSTALL_DIR location, everything should work out-of-the-box.

**Comment by DmitryLyakh** [comment]
Also, since you are specifying compilers explicitly via CC=gcc CXX=g++, you should also add FC=gfortran for completeness. With these settings, you do not need to redefine CMAKE_C_Compiler and CMAKE_CXX_Compiler in the CMAKE configure line.

**Comment by otbrown** [comment]
Thanks @DmitryLyakh that's worked. Much appreciated :)
