### ISSUE TITLE
Handle different cuQuantum SDK directory structure in CMake

### ISSUE THREAD

**Issue by 1tnguyen** [ORNL-QCI/exatn#49]
The path `${CUQUANTUM_PATH}/lib64/` may not be valid for all `cuQuantum` installations.
e.g., when I unzip the latest beta version, the path is `lib` **not** `lib64`.

**Comment by samstanwyck** [comment]
Hi Thien, yes that's a known issue that's in our pipeline to fix. In the meantime a rename or symlink should solve the problem.

**Comment by 1tnguyen** [comment]
This has been fixed in https://github.com/ORNL-QCI/exatn/commit/065dff13079ac59ebbde53d76e7d65e0acf6281c. Closing.
