### ISSUE TITLE
Mac OS X Build error -fopenmp, used g++ instead of CMAKE_CXX_COMPILER

### ISSUE THREAD

**Issue by amccaskey** [ORNL-QCI/exatn#8]
I just pulled a fresh version of the repo on my mac. I configured with 
```
FC=gfortran-8 CXX=g++-8 CC=gcc-8 cmake .. -DEXATN_BUILD_TESTS=TRUE
```

and ran make, and observed in the ExaTensor build

```
cd /Users/aqw/exatn/build && /usr/local/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E cmake_depends "Unix Makefiles" /Users/aqw/exatn /Users/aqw/exatn/tpls/boost-cmake /Users/aqw/exatn/build /Users/aqw/exatn/build/tpls/boost-cmake /Users/aqw/exatn/build/tpls/boost-cmake/CMakeFiles/Boost_regex.dir/DependInfo.cmake --color=
cd /Users/aqw/exatn/tpls/ExaTensor && /usr/local/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E env CPP_GNU=/usr/local/bin/g++-8 CC_GNU=/usr/local/bin/gcc-8 FC_GNU=/usr/local/bin/gfortran-8 GPU_CUDA=NOCUDA MPILIB=NONE BLASLIB=NONE EXA_NO_BUILD=NO PATH_NONE= EXA_TALSH_ONLY=YES EXATN_SERVICE=YES EXA_OS=NO_LINUX make
Dependee "/Users/aqw/exatn/build/tpls/boost-cmake/CMakeFiles/Boost_regex.dir/DependInfo.cmake" is newer than depender "/Users/aqw/exatn/build/tpls/boost-cmake/CMakeFiles/Boost_regex.dir/depend.internal".
Dependee "/Users/aqw/exatn/build/tpls/boost-cmake/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/aqw/exatn/build/tpls/boost-cmake/CMakeFiles/Boost_regex.dir/depend.internal".
Scanning dependencies of target Boost_regex
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ./TALSH
g++ -I. -I. -I. -c -O3 -fopenmp -DNO_GPU -DNO_AMD -DNO_PHI -DNO_BLAS -DNO_LINUX -fPIC -DEXATN_SERVICE -std=c++11 timer.cpp -o ./OBJ/timer.o
clang: error: unsupported option '-fopenmp'
make[4]: *** [OBJ/timer.o] Error 1
make[3]: *** [ExaTensor] Error 2
make[2]: *** [tpls/CMakeFiles/exatensor-build] Error 2
make[1]: *** [tpls/CMakeFiles/exatensor-build.dir/all] Error 2
```

even though CPP_GNU was set in tpls/CMakeLists.txt, it did not map down to TALSH/Makefile. I modifed CPP_GNU = g++ in TALSH/Makefile to ?= g++ and it worked.

**Comment by DmitryLyakh** [comment]
It looks to me that making ExaTensor part of the CMAKE build will keep breaking and it takes way too much time to fix. Should we instead reconsider and require users to build ExaTENSOR or TAL-SH standalone as a prerequisite for ExaTN. Then, ExaTN can just link with libexatensor.so or libtalsh.so, but this will still require adding openmp and cuda libraries in the linking line. Currently I do not necessarily have a good idea how to fix the build system for good ...

**Comment by amccaskey** [comment]
I've always found it difficult to integrate projects with CMake build systems with projects with standard Make build systems. But I'm not convinced that we should wave the white flag yet. I think the issues we are having are more so growing pains. The improvements Joe has made have been a great step in the right direction, we just need to iron out the kinks. I'll spend some time on this tomorrow with Joe.

If this continues going on for another week or two, I will definitely be open to pulling ExaTensor out as its own separate, manual build dependency.

**Comment by amccaskey** [comment]
Thinking about this a bit more...

The cool thing about CppMicroServices is that it allows developers to operate in their own sandbox implementing specific interfaces (plugins) that are then contributed to some core framework via installation to a specified folder. 

Since the only thing in ExaTN that requires ExaTensor/Talsh is the node_executors, we could consider pull ExaTensor out of ExaTN and instead just contribute a new ExaTensor folder that implements node_executors and exposes an Activator/etc in order to create a new node_executor plugin shared library that is installed to the correct plugins/ folder for exatn to see. I think this could all be done through the existing ExaTensor Makefile. 

In this way, ExaTN only cares about its core interfaces, and subtypes can be provided as external, sandboxed implementations. 

I think I like this approach a lot.

**Comment by DmitryLyakh** [comment]
Sounds like an interesting idea.

**Comment by DmitryLyakh** [comment]
I think a better solution to resolve this issue is the following. I can easily make ExaTENSOR/TALSH import CMAKE_CXX_COMPILER, CMAKE_C_COMPILER, CMAKE_Fortran_COMPILER variables from the environment as long as they are set in the make line created by CMAKE for building ExaTENSOR/TALSH. Are they set there (or can we set them there)? Then I will just import these three (did I spell them right?).

**Comment by amccaskey** [comment]
They aren’t set as env vars right now but we could set it up that way. You spelled them right. Just have to update the make lines in tpls/CMakeLists.txt to replace CPP_GNU=${CMAKE_CXX_COMPILER} to CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}, and the others similarly

**Comment by DmitryLyakh** [comment]
Ok, then I will go ahead and update ExaTENSOR/TALSH Makefiles to import these three variables when EXATN_SERVICE=YES. This mechanism will then work for any compiler suite, not just GNU.

**Comment by DmitryLyakh** [comment]
Once you update the CMakeLists.txt, go ahead and merge it into devel. I've just merge devel_dil (including mccaskey/devel_dil) into devel. It builds fine with no MPI and ATLAS BLAS.

**Comment by DmitryLyakh** [comment]
All ExaTENSOR/TALSH Makefiles will now import CMAKE_{C,CXX,Fortran}_COMPILER from CMAKE when EXATN_SERVICE=YES. Pushed to ExaTENSOR master branch. We need to move the ExaTENSOR submodule head to the top of the ExaTENSOR master branch.
