### ISSUE TITLE
Separate exatn:: API from exatn_service:: API

### ISSUE THREAD

**Issue by amccaskey** [ORNL-QCI/exatn#9]
We need a separate API for retrieving services from CppMicroServices

**Comment by DmitryLyakh** [comment]
Now exatn.hpp contains exatn_service.hpp (CppMicorServices API and initialization) and exatn_numerics.hpp (Numerical Server). exatn_service.hpp can also be used standalone. Pushed into branch devel.

**Comment by amccaskey** [comment]
I haven’t finished this one yet 😀😎

**Comment by amccaskey** [comment]
Just saw you did it
